# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build chocofi'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano"]'
      shield: '["corne_left","corne_right"]'
      kconfig: '["#enable power management\nCONFIG_ZMK_SLEEP=y\nCONFIG_ZMK_IDLE_SLEEP_TIMEOUT=3600000\n\n#enable bluetooth\nCONFIG_BT=y\nCONFIG_ZMK_BLE=y\nCONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y \n\n# Increase transmission strength.\nCONFIG_BT_CTLR_TX_PWR_PLUS_8=y\n\n# Display\nCONFIG_ZMK_DISPLAY=y\n#CONFIG_ZMK_DISPLAY_INVERT=y\nCONFIG_ZMK_WIDGET_LAYER_STATUS=y\nCONFIG_ZMK_WIDGET_BATTERY_STATUS=y\n#CONFIG_ZMK_WIDGET_BATTERY_STATUS_SHOW_PERCENTAGE=y\nCONFIG_ZMK_WIDGET_OUTPUT_STATUS=y\nCONFIG_ZMK_WIDGET_WPM_STATUS=y\n#CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y\nCONFIG_ZMK_DISPLAY_WORK_QUEUE_SYSTEM=y\n\nCONFIG_ZMK_KEYBOARD_NAME=\"Chocofi\"\n"]'


